# Generated by Django 2.1 on 2019-05-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='captain',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
    ]
