# Generated by Django 2.1 on 2019-05-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubtcomment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_comments', to='common.DoubtComment', verbose_name='上级评论'),
        ),
        migrations.AlterField(
            model_name='problemcomment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_comments', to='common.ProblemComment', verbose_name='上级评论'),
        ),
    ]
