# Generated by Django 2.1 on 2019-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190505_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_apply',
            field=models.BooleanField(default=False),
        ),
    ]
