# Generated by Django 2.1 on 2019-05-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_group_is_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='people_num',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
