# Generated by Django 2.1 on 2019-05-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190509_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
    ]
