# Generated by Django 2.1 on 2019-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20190505_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='group',
            field=models.ManyToManyField(default=None, to='common.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='people_num',
            field=models.IntegerField(default=0),
        ),
    ]
