# Generated by Django 2.1 on 2019-05-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20190506_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='group',
            field=models.ManyToManyField(default=None, related_name='contests', to='common.Group'),
        ),
    ]
