# Generated by Django 2.1 on 2019-05-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20190506_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='group',
            field=models.ManyToManyField(blank=True, default=None, related_name='contests', to='common.Group'),
        ),
    ]
