# Generated by Django 2.1 on 2019-05-08 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20190507_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubtcomment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doubtcomment_replied', to=settings.AUTH_USER_MODEL, verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='problemcomment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemcomment_replied', to=settings.AUTH_USER_MODEL, verbose_name='回复'),
        ),
    ]
