# Generated by Django 2.1.4 on 2019-03-12 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('time_cost', models.TimeField(default=(1900, 1, 1, 0, 0, 0, 0, 1, -1))),
                ('is_simulation', models.IntegerField(default=False, verbose_name='是否模拟')),
            ],
            options={
                'verbose_name': '竞赛成绩',
                'verbose_name_plural': '竞赛成绩',
                'db_table': 'contest_grade',
            },
        ),
        migrations.RemoveField(
            model_name='contest_grade',
            name='contest_id',
        ),
        migrations.RemoveField(
            model_name='contest_grade',
            name='user',
        ),
        migrations.AddField(
            model_name='contestcommitrecord',
            name='is_simulation',
            field=models.IntegerField(default=False, verbose_name='是否模拟'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='duration',
            field=models.IntegerField(default=300),
        ),
        migrations.DeleteModel(
            name='contest_grade',
        ),
        migrations.AddField(
            model_name='contestgrade',
            name='contest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
        migrations.AddField(
            model_name='contestgrade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
