# Generated by Django 2.1.4 on 2019-03-12 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0002_auto_20190312_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestProposer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '比赛报名表',
                'verbose_name_plural': '比赛报名表',
                'db_table': 'contest_proposer',
            },
        ),
        migrations.RemoveField(
            model_name='contest',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='start_date',
        ),
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contestproposer',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposer', to='contest.Contest'),
        ),
        migrations.AddField(
            model_name='contestproposer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
