# Generated by Django 2.1.5 on 2019-02-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mugshot',
            field=models.ImageField(default='/static/upload/mugshots/default.jpg', upload_to='upload/mugshots', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, verbose_name='昵称'),
        ),
    ]
