# Generated by Django 2.1.4 on 2019-03-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='是否队伍'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'is_group')},
        ),
    ]
