# Generated by Django 2.1.4 on 2019-01-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
                ('accepted_num', models.IntegerField(default=0, verbose_name='通过数量')),
                ('failed_num', models.IntegerField(default=0, verbose_name='失败数量')),
            ],
        ),
    ]
