# Generated by Django 2.1.4 on 2019-02-20 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(verbose_name='题目编号')),
                ('uid', models.IntegerField(verbose_name='用户编号')),
                ('status', models.BooleanField(verbose_name='状态')),
                ('result', models.CharField(max_length=20, verbose_name='结果')),
                ('cost_time', models.IntegerField(verbose_name='时间消耗')),
                ('cost_memory', models.IntegerField(verbose_name='内存消耗')),
                ('time_commited', models.DateField(auto_now=True, verbose_name='提交时间')),
                ('code', models.TextField(verbose_name='代码')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'db_table': 'commit_record',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='题目')),
                ('content', models.TextField(verbose_name='描述')),
                ('time_limited', models.IntegerField(default=1000, verbose_name='时间限制')),
                ('memory_limited', models.IntegerField(default=64, verbose_name='空间限制')),
                ('rank', models.IntegerField(verbose_name='等级')),
                ('in_description', models.TextField(verbose_name='输入描述')),
                ('out_description', models.TextField(verbose_name='输出描述')),
                ('in_case', models.TextField(verbose_name='样例输入')),
                ('out_case', models.TextField(verbose_name='样例输出')),
                ('source', models.CharField(max_length=50, verbose_name='来源')),
                ('tip', models.TextField(verbose_name='提示')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
                'db_table': 'problem',
            },
        ),
        migrations.CreateModel(
            name='ProblemCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'problem_catagory',
            },
        ),
        migrations.CreateModel(
            name='ProblemComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='正文')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否显示')),
                ('star', models.IntegerField(default=0, verbose_name='点赞')),
                ('is_problem_comment', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_comment_set', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('parent_comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='problem.ProblemComment', verbose_name='上级评论')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem', verbose_name='问题')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_commented_set', to=settings.AUTH_USER_MODEL, verbose_name='回复')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'problem_comments',
                'ordering': ['-created_time'],
                'get_latest_by': 'created_time',
            },
        ),
    ]
