# Generated by Django 2.1.4 on 2019-01-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(verbose_name='题目编号')),
                ('uid', models.IntegerField(verbose_name='用户编号')),
                ('status', models.BooleanField(verbose_name='状态')),
                ('result', models.CharField(max_length=20, verbose_name='结果')),
                ('cost_time', models.IntegerField(verbose_name='时间消耗')),
                ('cost_memory', models.IntegerField(verbose_name='内存消耗')),
                ('time_commited', models.DateField(auto_now=True, verbose_name='提交时间')),
                ('code', models.TextField(verbose_name='代码')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'db_table': 'commit_record',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='题目')),
                ('content', models.TextField(verbose_name='描述')),
                ('time_limited', models.IntegerField(default=1000, verbose_name='时间限制')),
                ('memory_limited', models.IntegerField(default=64, verbose_name='空间限制')),
                ('rank', models.IntegerField(verbose_name='等级')),
                ('in_description', models.TextField(verbose_name='输入描述')),
                ('out_description', models.TextField(verbose_name='输出描述')),
                ('in_case', models.TextField(verbose_name='样例输入')),
                ('out_case', models.TextField(verbose_name='样例输出')),
                ('source', models.CharField(max_length=50, verbose_name='来源')),
                ('tip', models.TextField(verbose_name='提示')),
                ('number_accepted', models.IntegerField(default=0, verbose_name='接受数量')),
                ('number_commited', models.IntegerField(default=0, verbose_name='提交数量')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
                'db_table': 'problem',
            },
        ),
    ]
