# Generated by Django 2.1.5 on 2019-02-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'problem_catagory',
            },
        ),
        migrations.RemoveField(
            model_name='problem',
            name='number_accepted',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='number_commited',
        ),
    ]
