# Generated by Django 2.1.4 on 2019-02-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='problemcomment',
            table='problem_comment',
        ),
    ]
