# Generated by Django 2.1.4 on 2019-02-20 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20190220_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.ProblemComment', verbose_name='上级评论'),
        ),
    ]
