# Generated by Django 2.1.4 on 2019-02-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20190220_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_comments', to='problem.ProblemComment', verbose_name='上级评论'),
        ),
    ]
