# Generated by Django 2.1.4 on 2019-03-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20190301_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitrecord',
            old_name='time_commited',
            new_name='created_time',
        ),
        migrations.AlterField(
            model_name='commitrecord',
            name='result',
            field=models.CharField(default='', max_length=20, verbose_name='结果'),
        ),
        migrations.AlterField(
            model_name='commitrecord',
            name='status',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
    ]
