# Generated by Django 2.1.4 on 2019-03-05 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_auto_20190305_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitrecord',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间'),
        ),
    ]
