# Generated by Django 2.1.4 on 2019-03-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_auto_20190305_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_display',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
